### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/swaglyrics-backend#6]
Add documentation

**Comment by JamesVStone** [comment]
On the topic of documentation and clarity do you think it would be a good idea to change the filename of of `issue_maker.py` to something like `server.py` as it is the entry point for the application.

**Comment by aadibajpai** [comment]
> On the topic of documentation and clarity do you think it would be a good idea to change the filename of of `issue_maker.py` to something like `server.py` as it is the entry point for the application.

Yes that should be the case, it's just that renaming it would require manual edits on the backend.

**Comment by JamesVStone** [comment]
Ok, it is probably worth leaving that for a bigger PR then. If we are doing that it may be works setting it up as a python package with a `__init__.py` as suggest in [flask docs](https://flask.palletsprojects.com/en/1.1.x/patterns/packages/#simple-packages)

**Comment by aadibajpai** [comment]
fwiw documentation is much better now
